//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Safe_Task_Analysis.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new step.
        /// </summary>
        public static string AddTaskDesc {
            get {
                return ResourceManager.GetString("AddTaskDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checklist.
        /// </summary>
        public static string AideMemoire {
            get {
                return ResourceManager.GetString("AideMemoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        public static string ByJSA {
            get {
                return ResourceManager.GetString("ByJSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General informations :.
        /// </summary>
        public static string GeneralInformations {
            get {
                return ResourceManager.GetString("GeneralInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAFC Online.
        /// </summary>
        public static string GlobalAAFCOnline {
            get {
                return ResourceManager.GetString("GlobalAAFCOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.agr.gc.ca/index_e.php.
        /// </summary>
        public static string GlobalAAFCOnlineURL {
            get {
                return ResourceManager.GetString("GlobalAAFCOnlineURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string GlobalAdd {
            get {
                return ResourceManager.GetString("GlobalAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics of the application.
        /// </summary>
        public static string GlobalAdminStatistics {
            get {
                return ResourceManager.GetString("GlobalAdminStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string GlobalAll {
            get {
                return ResourceManager.GetString("GlobalAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string GlobalAuthor {
            get {
                return ResourceManager.GetString("GlobalAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string GlobalCancel {
            get {
                return ResourceManager.GetString("GlobalCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string GlobalContact {
            get {
                return ResourceManager.GetString("GlobalContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to a new JSA.
        /// </summary>
        public static string GlobalCopy {
            get {
                return ResourceManager.GetString("GlobalCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date.
        /// </summary>
        public static string GlobalCreateDate {
            get {
                return ResourceManager.GetString("GlobalCreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eng.
        /// </summary>
        public static string GlobalCurrentLang {
            get {
                return ResourceManager.GetString("GlobalCurrentLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string GlobalDelete {
            get {
                return ResourceManager.GetString("GlobalDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string GlobalEdit {
            get {
                return ResourceManager.GetString("GlobalEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in the blank !.
        /// </summary>
        public static string GlobalError1 {
            get {
                return ResourceManager.GetString("GlobalError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task failed !.
        /// </summary>
        public static string GlobalError2 {
            get {
                return ResourceManager.GetString("GlobalError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to PDF.
        /// </summary>
        public static string GlobalExportPDF {
            get {
                return ResourceManager.GetString("GlobalExportPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string GlobalFinish {
            get {
                return ResourceManager.GetString("GlobalFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string GlobalHelp {
            get {
                return ResourceManager.GetString("GlobalHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string GlobalHome {
            get {
                return ResourceManager.GetString("GlobalHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important Notice.
        /// </summary>
        public static string GlobalImportantNotice {
            get {
                return ResourceManager.GetString("GlobalImportantNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modification by.
        /// </summary>
        public static string GlobalModAuthor {
            get {
                return ResourceManager.GetString("GlobalModAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modified.
        /// </summary>
        public static string GlobalModDate {
            get {
                return ResourceManager.GetString("GlobalModDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date modified.
        /// </summary>
        public static string GlobalModificationDate {
            get {
                return ResourceManager.GetString("GlobalModificationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string GlobalModify {
            get {
                return ResourceManager.GetString("GlobalModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        public static string GlobalMoveDown {
            get {
                return ResourceManager.GetString("GlobalMoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        public static string GlobalMoveUp {
            get {
                return ResourceManager.GetString("GlobalMoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string GlobalNone {
            get {
                return ResourceManager.GetString("GlobalNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top of Page.
        /// </summary>
        public static string GlobalPageTop {
            get {
                return ResourceManager.GetString("GlobalPageTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string GlobalPrint {
            get {
                return ResourceManager.GetString("GlobalPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publiservice.
        /// </summary>
        public static string GlobalPubliservice {
            get {
                return ResourceManager.GetString("GlobalPubliservice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string GlobalReturn {
            get {
                return ResourceManager.GetString("GlobalReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Safety Analysis.
        /// </summary>
        public static string GlobalSafeTaskAnalysisTitle {
            get {
                return ResourceManager.GetString("GlobalSafeTaskAnalysisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string GlobalSave {
            get {
                return ResourceManager.GetString("GlobalSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sig-eng.gif.
        /// </summary>
        public static string GlobalSigName {
            get {
                return ResourceManager.GetString("GlobalSigName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        public static string GlobalSort {
            get {
                return ResourceManager.GetString("GlobalSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success !.
        /// </summary>
        public static string GlobalSuccess {
            get {
                return ResourceManager.GetString("GlobalSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fra.
        /// </summary>
        public static string GlobalSwitchLang {
            get {
                return ResourceManager.GetString("GlobalSwitchLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        public static string GlobalSwitchLanguage {
            get {
                return ResourceManager.GetString("GlobalSwitchLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string GlobalUpdate {
            get {
                return ResourceManager.GetString("GlobalUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach the file.
        /// </summary>
        public static string GlobalUpload {
            get {
                return ResourceManager.GetString("GlobalUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QcSthyaweb3/JSA.
        /// </summary>
        public static string GlobalWebAddr {
            get {
                return ResourceManager.GetString("GlobalWebAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrate the application.
        /// </summary>
        public static string HomeIndex2Admin {
            get {
                return ResourceManager.GetString("HomeIndex2Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body of index 2 page in English.
        /// </summary>
        public static string HomeIndex2Body {
            get {
                return ResourceManager.GetString("HomeIndex2Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Job Safety Analysis (JSA) process provides a way of identifying job-related hazards and determining preventive measures. .
        /// </summary>
        public static string HomeIndex2Desc1 {
            get {
                return ResourceManager.GetString("HomeIndex2Desc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This involves carefully analysing each task of a job, identifying potential health and safety hazards at each step and determining practical ways of preventing or mitigating such hazards..
        /// </summary>
        public static string HomeIndex2Desc2 {
            get {
                return ResourceManager.GetString("HomeIndex2Desc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These preventive measures can then be integrated into an employer’s work practices and procedures for the job..
        /// </summary>
        public static string HomeIndex2Desc3 {
            get {
                return ResourceManager.GetString("HomeIndex2Desc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new JSA.
        /// </summary>
        public static string HomeIndex2NewAST {
            get {
                return ResourceManager.GetString("HomeIndex2NewAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recall highlights of the OHS-500 training on Job Safety  Analysis of Safe (JSA).
        /// </summary>
        public static string HomeIndex2Objective1 {
            get {
                return ResourceManager.GetString("HomeIndex2Objective1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explain the registration steps of JSAs by using the archive and writing tool available.
        /// </summary>
        public static string HomeIndex2Objective2 {
            get {
                return ResourceManager.GetString("HomeIndex2Objective2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promote the sharing of information on JSA in the Department.
        /// </summary>
        public static string HomeIndex2Objective3 {
            get {
                return ResourceManager.GetString("HomeIndex2Objective3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database objectives :.
        /// </summary>
        public static string HomeIndex2Objectives {
            get {
                return ResourceManager.GetString("HomeIndex2Objectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search existing JSAs.
        /// </summary>
        public static string HomeIndex2SearchAST {
            get {
                return ResourceManager.GetString("HomeIndex2SearchAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consult a basic training on JSA.
        /// </summary>
        public static string HomeIndex2Tuto {
            get {
                return ResourceManager.GetString("HomeIndex2Tuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose any of the following options:.
        /// </summary>
        public static string HomeIndex2WTD {
            get {
                return ResourceManager.GetString("HomeIndex2WTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Safety Analysis (JSA).
        /// </summary>
        public static string HomeIndexBody1 {
            get {
                return ResourceManager.GetString("HomeIndexBody1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyse Sécuritaire de Tâches.
        /// </summary>
        public static string HomeIndexBody2 {
            get {
                return ResourceManager.GetString("HomeIndexBody2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Safety Analysis / Analyse Sécuritaire de Tâches.
        /// </summary>
        public static string HomeIndexTitle {
            get {
                return ResourceManager.GetString("HomeIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a standard writing template integrating information’s to the Departmental database.
        /// </summary>
        public static string HomeJSATitle1 {
            get {
                return ResourceManager.GetString("HomeJSATitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualize JSAs available and adapt it to personal situations.
        /// </summary>
        public static string HomeJSATitle2 {
            get {
                return ResourceManager.GetString("HomeJSATitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tutorial that explains the process of writing a JSA step by step
        ///(recommended at first occurrence).
        /// </summary>
        public static string HomeJSATitle3 {
            get {
                return ResourceManager.GetString("HomeJSATitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable the menus modification, compilation, archiving and monitoring.
        /// </summary>
        public static string HomeJSATitle4 {
            get {
                return ResourceManager.GetString("HomeJSATitle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to do ? Here&apos;s a list of all availables choices :.
        /// </summary>
        public static string JSAAdminPres {
            get {
                return ResourceManager.GetString("JSAAdminPres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associated.
        /// </summary>
        public static string JSAAssociated {
            get {
                return ResourceManager.GetString("JSAAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take some time to check whether the informations in the table are corrects. Then, correct the header and add a taskname for this JSA..
        /// </summary>
        public static string JSACopyInfos {
            get {
                return ResourceManager.GetString("JSACopyInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new.
        /// </summary>
        public static string JSACreateNew {
            get {
                return ResourceManager.GetString("JSACreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new.
        /// </summary>
        public static string JSACreateNewe {
            get {
                return ResourceManager.GetString("JSACreateNewe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a supervisor with the following format : Last Name, First Name.
        /// </summary>
        public static string JSACreateSupervisorInstructions {
            get {
                return ResourceManager.GetString("JSACreateSupervisorInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSAs in the database !.
        /// </summary>
        public static string JSADB {
            get {
                return ResourceManager.GetString("JSADB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associated document.
        /// </summary>
        public static string JSADocumentAssociated {
            get {
                return ResourceManager.GetString("JSADocumentAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None required.
        /// </summary>
        public static string JSAexportPdfNoneRequired {
            get {
                return ResourceManager.GetString("JSAexportPdfNoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics of the application.
        /// </summary>
        public static string JSAGlobalStats {
            get {
                return ResourceManager.GetString("JSAGlobalStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The next steps are directly related to the writing of your JSA.
        ///Keep in mind that you will be able to enhance your JSA with these optional features :.
        /// </summary>
        public static string JSAGoingToStep67 {
            get {
                return ResourceManager.GetString("JSAGoingToStep67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Personal Protective Equipment icons.
        /// </summary>
        public static string JSAGoingToStep671 {
            get {
                return ResourceManager.GetString("JSAGoingToStep671", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add General Information to introduce your document.
        /// </summary>
        public static string JSAGoingToStep672 {
            get {
                return ResourceManager.GetString("JSAGoingToStep672", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach additional documents to your JSA.
        /// </summary>
        public static string JSAGoingToStep673 {
            get {
                return ResourceManager.GetString("JSAGoingToStep673", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1/7 : Choice of the job to analyse.
        /// </summary>
        public static string JSAHeader1 {
            get {
                return ResourceManager.GetString("JSAHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2/7 : Fill the informations needed for an accurate storage.
        /// </summary>
        public static string JSAHeader2 {
            get {
                return ResourceManager.GetString("JSAHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add associated risk.
        /// </summary>
        public static string JSAIndexAddAssRisk {
            get {
                return ResourceManager.GetString("JSAIndexAddAssRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a preventive measure.
        /// </summary>
        public static string JSAIndexAddPrevMes {
            get {
                return ResourceManager.GetString("JSAIndexAddPrevMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 4/7 : Add an associated risk.
        /// </summary>
        public static string JSAIndexAddRisk {
            get {
                return ResourceManager.GetString("JSAIndexAddRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3/7 : Add a task.
        /// </summary>
        public static string JSAIndexAddTask {
            get {
                return ResourceManager.GetString("JSAIndexAddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string JSAIndexAdmin {
            get {
                return ResourceManager.GetString("JSAIndexAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrators.
        /// </summary>
        public static string JSAIndexAdmins {
            get {
                return ResourceManager.GetString("JSAIndexAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string JSAIndexBranch {
            get {
                return ResourceManager.GetString("JSAIndexBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branchs.
        /// </summary>
        public static string JSAIndexBranchs {
            get {
                return ResourceManager.GetString("JSAIndexBranchs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please chose an administrator.
        /// </summary>
        public static string JSAIndexChooseAdmin {
            get {
                return ResourceManager.GetString("JSAIndexChooseAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please chose an author.
        /// </summary>
        public static string JSAIndexChooseAuthor {
            get {
                return ResourceManager.GetString("JSAIndexChooseAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a branch.
        /// </summary>
        public static string JSAIndexChooseBranch {
            get {
                return ResourceManager.GetString("JSAIndexChooseBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an environment.
        /// </summary>
        public static string JSAIndexChooseEnvironment {
            get {
                return ResourceManager.GetString("JSAIndexChooseEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an organisation.
        /// </summary>
        public static string JSAIndexChooseOrganisation {
            get {
                return ResourceManager.GetString("JSAIndexChooseOrganisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a potential risk.
        /// </summary>
        public static string JSAIndexChoosePotentialRisk {
            get {
                return ResourceManager.GetString("JSAIndexChoosePotentialRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a region.
        /// </summary>
        public static string JSAIndexChooseRegion {
            get {
                return ResourceManager.GetString("JSAIndexChooseRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a risk category.
        /// </summary>
        public static string JSAIndexChooseRiskCat {
            get {
                return ResourceManager.GetString("JSAIndexChooseRiskCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose the required safety equipment..
        /// </summary>
        public static string JSAIndexChooseSafetyEquip {
            get {
                return ResourceManager.GetString("JSAIndexChooseSafetyEquip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a supervisor.
        /// </summary>
        public static string JSAIndexChooseSupervisor {
            get {
                return ResourceManager.GetString("JSAIndexChooseSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for this task.
        /// </summary>
        public static string JSAIndexChooseTaskName {
            get {
                return ResourceManager.GetString("JSAIndexChooseTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 5/7 : Add a preventive mesure.
        /// </summary>
        public static string JSAIndexEnterPrevMes {
            get {
                return ResourceManager.GetString("JSAIndexEnterPrevMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new risk.
        /// </summary>
        public static string JSAIndexEnterRisk {
            get {
                return ResourceManager.GetString("JSAIndexEnterRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new step.
        /// </summary>
        public static string JSAIndexEnterTaskDesc {
            get {
                return ResourceManager.GetString("JSAIndexEnterTaskDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        public static string JSAIndexEnvironment {
            get {
                return ResourceManager.GetString("JSAIndexEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environments.
        /// </summary>
        public static string JSAIndexEnvironments {
            get {
                return ResourceManager.GetString("JSAIndexEnvironments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management of.
        /// </summary>
        public static string JSAIndexGestion {
            get {
                return ResourceManager.GetString("JSAIndexGestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit JSA.
        /// </summary>
        public static string JSAIndexModifyJSA {
            get {
                return ResourceManager.GetString("JSAIndexModifyJSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSA.
        /// </summary>
        public static string JSAIndexModifyJSAe {
            get {
                return ResourceManager.GetString("JSAIndexModifyJSAe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New JSA.
        /// </summary>
        public static string JSAIndexNewJSA {
            get {
                return ResourceManager.GetString("JSAIndexNewJSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Job Safety Analysis.
        /// </summary>
        public static string JSAIndexNewJSAe {
            get {
                return ResourceManager.GetString("JSAIndexNewJSAe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation.
        /// </summary>
        public static string JSAIndexOrganisation {
            get {
                return ResourceManager.GetString("JSAIndexOrganisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisations.
        /// </summary>
        public static string JSAIndexOrganisations {
            get {
                return ResourceManager.GetString("JSAIndexOrganisations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potential Risks.
        /// </summary>
        public static string JSAIndexPotentialRisk {
            get {
                return ResourceManager.GetString("JSAIndexPotentialRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preventive Measures.
        /// </summary>
        public static string JSAIndexPreventiveMesures {
            get {
                return ResourceManager.GetString("JSAIndexPreventiveMesures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string JSAIndexRegion {
            get {
                return ResourceManager.GetString("JSAIndexRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions.
        /// </summary>
        public static string JSAIndexRegions {
            get {
                return ResourceManager.GetString("JSAIndexRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety Equipment.
        /// </summary>
        public static string JSAIndexSafeTyEquip {
            get {
                return ResourceManager.GetString("JSAIndexSafeTyEquip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        public static string JSAIndexSupervisor {
            get {
                return ResourceManager.GetString("JSAIndexSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisors.
        /// </summary>
        public static string JSAIndexSupervisors {
            get {
                return ResourceManager.GetString("JSAIndexSupervisors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete.
        /// </summary>
        public static string JSAIndexSureDelete1 {
            get {
                return ResourceManager.GetString("JSAIndexSureDelete1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and all its related risks and preventive mesures ? This cannot be reversed..
        /// </summary>
        public static string JSAIndexSureDelete2 {
            get {
                return ResourceManager.GetString("JSAIndexSureDelete2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and all its related preventive mesures ? This cannot be reversed..
        /// </summary>
        public static string JSAIndexSureDelete3 {
            get {
                return ResourceManager.GetString("JSAIndexSureDelete3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ? This CANNOT be reversed..
        /// </summary>
        public static string JSAIndexSureDelete4 {
            get {
                return ResourceManager.GetString("JSAIndexSureDelete4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks order.
        /// </summary>
        public static string JSAIndexTaskOrder {
            get {
                return ResourceManager.GetString("JSAIndexTaskOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string JSAIndexTaskToAnalize {
            get {
                return ResourceManager.GetString("JSAIndexTaskToAnalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Safety Analysis.
        /// </summary>
        public static string JSAIndexTitle {
            get {
                return ResourceManager.GetString("JSAIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of the.
        /// </summary>
        public static string JSALister {
            get {
                return ResourceManager.GetString("JSALister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email this JSA.
        /// </summary>
        public static string JSAMailTo {
            get {
                return ResourceManager.GetString("JSAMailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Windows login.
        /// </summary>
        public static string JSANewAdmin {
            get {
                return ResourceManager.GetString("JSANewAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSA(s) for your research :.
        /// </summary>
        public static string JSASearch {
            get {
                return ResourceManager.GetString("JSASearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 6/7 : Communicating to employees concerned.
        /// </summary>
        public static string JSAStep6 {
            get {
                return ResourceManager.GetString("JSAStep6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send JSA to employees who will perform the job.
        /// </summary>
        public static string JSAStep6a {
            get {
                return ResourceManager.GetString("JSAStep6a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add JSA to any existing protocol or procedure if required.
        /// </summary>
        public static string JSAStep6b {
            get {
                return ResourceManager.GetString("JSAStep6b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide training to new employees by using JSA.
        /// </summary>
        public static string JSAStep6c {
            get {
                return ResourceManager.GetString("JSAStep6c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 7/7 : Periodic Review.
        /// </summary>
        public static string JSAStep7 {
            get {
                return ResourceManager.GetString("JSAStep7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revise JSA when the task changes.
        /// </summary>
        public static string JSAStep7a {
            get {
                return ResourceManager.GetString("JSAStep7a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revise JSA when a new hazard is detected.
        /// </summary>
        public static string JSAStep7b {
            get {
                return ResourceManager.GetString("JSAStep7b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Local Health and Safety Committee (or OHS representative) will determine the local revision process applicable for your JSA.
        /// </summary>
        public static string JSAStep7c {
            get {
                return ResourceManager.GetString("JSAStep7c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are .
        /// </summary>
        public static string JSAThere {
            get {
                return ResourceManager.GetString("JSAThere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purposes of information’s collection are to compile, archive and ensure the periodic review of JSAs for  supervisors, managers, Local OHS Committees (or OHS representatives), Regional OHS Coordinators or National Policy Committee.
        ///
        ///Precise reports creation and sorting information’s first required the specification of the following fields:.
        /// </summary>
        public static string JSATipHeader {
            get {
                return ResourceManager.GetString("JSATipHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This step is determining ways to eliminate or mitigate the hazards identified by following common hazard control strategies, in order of preference :.
        /// </summary>
        public static string JSATipPrevMes {
            get {
                return ResourceManager.GetString("JSATipPrevMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The eliminate the hazard;.
        /// </summary>
        public static string JSATipPrevMes1 {
            get {
                return ResourceManager.GetString("JSATipPrevMes1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reduction of hazard, including isolating it;.
        /// </summary>
        public static string JSATipPrevMes2 {
            get {
                return ResourceManager.GetString("JSATipPrevMes2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provision of personal protective equipment, clothing, devices or materials;.
        /// </summary>
        public static string JSATipPrevMes3 {
            get {
                return ResourceManager.GetString("JSATipPrevMes3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administratives procedures..
        /// </summary>
        public static string JSATipPrevMes4 {
            get {
                return ResourceManager.GetString("JSATipPrevMes4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to identify hazards associated to your job step.
        ///
        ///To help you, see the checklist that regroup typical hazards by categories and expose the most common examples..
        /// </summary>
        public static string JSATipRisk {
            get {
                return ResourceManager.GetString("JSATipRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associates hazards as much as you can find for each tasks.
        /// </summary>
        public static string JSATipRisk1 {
            get {
                return ResourceManager.GetString("JSATipRisk1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use short, clear and concise terminology to expose the hazard nature.
        /// </summary>
        public static string JSATipRisk2 {
            get {
                return ResourceManager.GetString("JSATipRisk2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid the use of too general hazard (ex: hazardous to health, risk of dying) or too specific (ex: can cause third degree burn).
        /// </summary>
        public static string JSATipRisk3 {
            get {
                return ResourceManager.GetString("JSATipRisk3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A rule of thumb is that most jobs can be described in less than ten tasks. Otherwise, it is recommended to split the job, each segment subject to a distinct JSA. Tips :.
        /// </summary>
        public static string JSATipTask {
            get {
                return ResourceManager.GetString("JSATipTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep the tasks in their correct chronological sequence.
        /// </summary>
        public static string JSATipTask1 {
            get {
                return ResourceManager.GetString("JSATipTask1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with an action verb, short, accurate, concise.
        /// </summary>
        public static string JSATipTask2 {
            get {
                return ResourceManager.GetString("JSATipTask2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid to present the statement in his negative form using &quot;Do not&quot;.
        /// </summary>
        public static string JSATipTask3 {
            get {
                return ResourceManager.GetString("JSATipTask3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes should be made of what is to be done rather than how it is done.
        /// </summary>
        public static string JSATipTask4 {
            get {
                return ResourceManager.GetString("JSATipTask4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideally, a JSA should be performed for all jobs. However, there are practical constraints on time and resources. For these reasons, it is usually necessary to set priorities.
        ///
        ///Your manager or supervisor has probably provided you reasons that motivate the actual creating process of you JSA..
        /// </summary>
        public static string JSATipTaskName {
            get {
                return ResourceManager.GetString("JSATipTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search an existing JSA.
        /// </summary>
        public static string SearchJSA {
            get {
                return ResourceManager.GetString("SearchJSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consult the PowerPoint of the application.
        /// </summary>
        public static string Tuto1 {
            get {
                return ResourceManager.GetString("Tuto1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consult an example of completed JSA.
        /// </summary>
        public static string Tuto2 {
            get {
                return ResourceManager.GetString("Tuto2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        public static string TutorialJSA {
            get {
                return ResourceManager.GetString("TutorialJSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified Supervisor.
        /// </summary>
        public static string UnspecifiedSup {
            get {
                return ResourceManager.GetString("UnspecifiedSup", resourceCulture);
            }
        }
    }
}
